### PR TITLE
feat: support downloading goreleaser pro

### PR DESCRIPTION
**Pull request by caarlos0**
:)

### CODE REVIEW

**Review by boban578 — APPROVED** [review]

**Comment by crazy-max** [comment]
@caarlos0 Maybe `GORELEASER_KEY` should be enough to download the right dist binary? This way we could remove the `distribution` input WDYT? If you want to add in the future an "enterprise" distribution maybe you could add a prefix to your `GORELEASER_KEY` we could use to also identify the right dist like:

* `GORELEASER_KEY=pro_a1cf8462-6364-48b2-aa6d-1026f5a211da`
* `GORELEASER_KEY=ent_a1cf8462-6364-48b2-aa6d-1026f5a211da`

WDYT?

**Comment by caarlos0** [comment]
hmm, yeah, that makes sense... let me try and change it :)

**Comment by caarlos0** [comment]
actually, the user might pass `--key` instead of the env, so its better leave as-is IMHO...

**Review by crazy-max — APPROVED** [review]
LGTM :)

**Pull request merged**
