### PR TITLE
fix: correctly check against list of tags

### LINKED ISSUE #27: Requirement of GITHUB_REF causing limitations
Hi all,

The change to require a GITHUB_REF for the action to run is causing some inconveniences that will limit adoption of this action.

If you want GITHUB_REF to be populated with a tag, the action trigger event needs to be something like `on: create` or `on: release` which is usually fine.

The problem is, if you're using another project to manage your tags and releases like https://github.com/semantic-release/github, then those tag events are created (by default) using the default GH Action token.

This GH Action Token is special in that it does NOT trigger other events as to avoid an infinite loop. This is an explicit feature/decision by the GH Actions team.

This means that I couldn't have semantic-release run as one workflow to trigger the goreleaser workflow, but ideally no human is the one pushing tags.

This leaves us with one of two options:

You could create a personal access token for whatever flow is pushing tags. Since it's a PAT, the `on: release` and `on: create` workflows will trigger. This is not ideal because now you have to create a PAT which means you have to tie that execution to a person. Since there's no way to create organizational access tokens, you'll have to create another user to be a service user in GitHub which could cost you money.

The second option is to install goreleaser directly to the GitHub Action Runner itself like so:
```
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -Lo /tmp/goreleaser.tar.gz https://github.com/goreleaser/goreleaser/releases/download/v0.120.3/goreleaser_Linux_x86_64.tar.gz
        tar -xzvf /tmp/goreleaser.tar.gz -C /tmp/
        /tmp/goreleaser release
```

This is not ideal because now I'm coupled to expectations of what is installed in the Runner environment, instead of getting an isolated container to run in.

Could we remove the requirement of a GITHUB_REF?

### PR DESCRIPTION
**Pull request by abatilo**
Instead of assuming that we'll have an event where the GITHUB_REF is for
a tag, let's actually check for the available tags using the GitHub API.

@crazy-max I'm not a node/JS/TS developer at all, so please let me know if this is to your liking.

Fixes #27

### CODE REVIEW

**Comment by caarlos0** [comment]
pretty sure you shouldn't have pushed your node_modules...

**Comment by abatilo** [comment]
> pretty sure you shouldn't have pushed your node_modules...

I thought so as well... until I noticed that there are node_modules pushed into the repo...

Also, I kept getting "package not found" up until I did push it. It doesn't appear that any kind of `npm install` is done when the action is ran?

**Comment by abatilo** [comment]
@caarlos0 
https://github.com/goreleaser/goreleaser-action/pull/29/checks?check_run_id=282576190#step:4:11
The moment I remove the node_modules, I receive this error.

**Comment by abatilo** [comment]
Could someone give me a hand in understanding this error message:
https://github.com/goreleaser/goreleaser-action/pull/29/checks?check_run_id=282579778#step:4:22

>⨯ release failed after 0.60s error=git tag v1.0.0 was not made against commit 80a69aebc482056803aeeddc0549efd3d8d6fdac

Is this because this commit is coming from a fork?

**Comment by crazy-max** [comment]
@abatilo This is because you are looking for a tag no matter what the commit is and it's not way so goreleaser works. After digging, the recommended way to verify the presence of a git tag through GitHub Actions is to use the `GITHUB_REF` environment variable as [stipulated by the GitHub staff](https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027).

**Pull request closed without merging**
