### PR TITLE
fix: do not override GORELEASER_CURRENT_TAG

### PR DESCRIPTION
**Pull request by caarlos0**
we shouldn't really do this.. as when using monorepo.tag_prefix it'll set the wrong tag to goreleaser.

that said, I'm not really sure about the auto-snapshot thingy too... seems easy enough to check on the workflow if the current commit is a tag or not, and act accordingly, no?

### CODE REVIEW

**Comment by crazy-max** [comment]
> that said, I'm not really sure about the auto-snapshot thingy too... seems easy enough to check on the workflow if the current commit is a tag or not, and act accordingly, no?

Yes this was added to ease the integration in the workflow otherwise `release` command would fail on smth else that release tag. I guess we could make it optional.

**Comment by caarlos0** [comment]
at this point, I think we could actually make the action simpler and just download and run goreleaser without doing anything else.

we don't even need javascript for that, see https://github.com/sigstore/cosign-installer/blob/main/action.yml for example

**Comment by caarlos0** [comment]
cc/ @cpanato since you maintain the cosign action... anything you would like to share about your approach? does it work well? anything you wish to have done differently? do you automate the action release et al?

thankss <3

**Comment by cpanato** [comment]
my personal option is either you just have an action to install the tool and make sure you are installing correctly (checking signatures/shasums...) or you are very opinionated in how to expose the options to run the tool, otherwise, you will have to maintain a lot of corner cases and some are just for a really smaller audience.

**Comment by caarlos0** [comment]
@crazy-max FWIW gonna release this

**Comment by crazy-max** [comment]
@caarlos0 Major bump was the right move, thanks!

**Pull request merged**
