### PR TITLE
chore: update yarn to 3.5.1

### PR DESCRIPTION
**Pull request by crazy-max**
See https://yarnpkg.com/getting-started/migration

```bash
$ npm install -g yarn
# https://yarnpkg.com/getting-started/install#updating-to-the-latest-versions
$ yarn set version stable
```

Also install plugin-interactive-tools yarn pkg: https://yarnpkg.com/api/modules/plugin_interactive_tools.html

```bash
$ yarn plugin import interactive-tools
```

### CODE REVIEW

**Comment by caarlos0** [comment]
shouldn't `.yarn` be gitignored?

**Comment by crazy-max** [comment]
> shouldn't `.yarn` be gitignored?

Only some subdirs actually: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

**Review by caarlos0 — APPROVED** [review]

**Review by caarlos0 — APPROVED** [review]

**Comment by caarlos0** [comment]
dupe approval, wth hehe

**Comment by caarlos0** [comment]
thanks for working on this, @crazy-max

**Comment by crazy-max** [comment]
Sure np! I'm looking at #397 to fix the parsing issue.

**Pull request merged**
