### PR TITLE
chore: update generated content

### PR DESCRIPTION
**Pull request by crazy-max**
relates to https://github.com/goreleaser/goreleaser-action/actions/runs/11715158853/job/32631069786#step:3:291

```
  > [build-validate 1/1] RUN --mount=type=bind,target=.,rw <<EOT (set -e...):
0.214 ERROR: Build result differs. Please build first with "docker buildx bake build"
0.217  M dist/index.js
0.217  M dist/index.js.map
```

@caarlos0 Seems to be an oversight when https://github.com/goreleaser/goreleaser-action/pull/478 and other failed PRs have been merged: https://github.com/goreleaser/goreleaser-action/pulls?q=is%3Apr+is%3Aclosed

image

The build validate check is red though:

image

Before merging dependabot or when updating dependencies, you need to make sure dist is up to date otherwise the update is not used when the action is consumed. For that you need to run `docker buildx bake pre-checkin` and push changes similar to https://github.com/docker/setup-buildx-action/pull/370: https://github.com/docker/setup-buildx-action/pull/370/commits/93aa1c807f4b7b4127247ca869271da7d2d752ea

image

### CODE REVIEW

**Comment by caarlos0** [comment]
I guess we can probably automate that? 

I completely forgot I had to run that tbh

**Review by caarlos0 — APPROVED** [review]

**Comment by crazy-max** [comment]
> I guess we can probably automate that?

I don't think we can as depdendabot can't trigger another worflow

**Comment by caarlos0** [comment]
> > I guess we can probably automate that?
> 
> I don't think we can as depdendabot can't trigger another worflow

ah, right

**Comment by caarlos0** [comment]
so maybe a daily run? so worst case its out of date for 24h 🤔

**Pull request merged**
