### PR TITLE
feat!: remove auto-snapshot on dirty tag

### LINKED ISSUE #380: Supprt tags in sub ref directory?
The code says:

https://github.com/goreleaser/goreleaser-action/blob/b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757/src/git.ts#L19-L24

If `GITHUB_REF=refs/tags/release/0.1.0`, then the `tag` will be `0.1.0`, but it should be `release/0.1.0`

Is the `pop` done by purpose? Could it support `release/0.1.0` and use `0.1.0` as the version?

### PR DESCRIPTION
**Pull request by caarlos0**
closes #380

### CODE REVIEW

**Comment by crazy-max** [comment]
Sorry didn't have time to review this :persevere: but lgtm

**Comment by caarlos0** [comment]
No worries ❤️

**Comment by meain** [comment]
Can I get the previous behavior of using snapshot if dirty and version of tagged by adding `--snapshot` to the args or will I have to separately handle them in each case?

**Comment by caarlos0** [comment]
there's a `--auto-snapshot` flag that enables it if the tree is dirty, you can either use that + a step to make the tree dirty on purpose that only runs when HEAD is not a tag, split the workflow into 2 (one for tags that never snapshots, one for commits that always snapshots), or handle with if statements. 

FWIW: I do something similar here https://github.com/caarlos0/goreleaser-pro-split-merge-example/blob/99553a5ca10b82335ae995083210957bb574ff8a/.github/workflows/nightly.yml#L23 for nightly on `workflow_dispatch`.

**Pull request merged**
